version: "3"
services:
  server:
    build:
      context: .
    ports: 
      - "8000:8000"
    expose: 
      - "8000"
    depends_on:
      - meilisearch
      - postgres
    networks:
      - virtualpaper
    environment:
      - VIRTUALPAPER_MEILISEARCH_URL=http://meilisearch:7700
      - VIRTUALPAPER_DATABASE_HOST=postgres
      - VIRTUALPAPER_DATABASE_PASSWORD=virtualpaper
      - VIRTUALPAPER_DATABASE_DATABASE=virtualpaper
      - VIRTUALPAPER_DATABASE_USERNAME=virtualpaper
      - VIRTUALPAPER_DATABASE_NO_SSL=true
      - VIRTUALPAPER_API_HOST=0.0.0.0
      - VIRTUALPAPER_LOGGING_LOG_LEVEL=DEBUG

    volumes:
      - virtualpaper_data:/data
      - virtualpaper_config:/config

  meilisearch:
    image: getmeili/meilisearch:v1.5.0
    networks:
      - virtualpaper
    volumes:
      - meilisearch:/meili_data

  postgres:
    image: postgres:14.2-alpine3.15
    environment:
      - POSTGRES_USER=virtualpaper
      - POSTGRES_PASSWORD=virtualpaper
      - POSTGRES_DB=virtualpaper
    networks:
      - virtualpaper
    volumes:
      - postgres:/var/lib/postgres

networks:
  virtualpaper:
    driver: bridge


volumes:
  meilisearch:
    name: virtualpaper_meilisearch${TEST_VOLUME_ID}
  postgres:
    name: virtualpaper_postgres${TEST_VOLUME_ID}
  virtualpaper_data:
    name: virtualpaper_data${TEST_VOLUME_ID}
  virtualpaper_config:
    name: virtualpaper_config${TEST_VOLUME_ID}



