package services

import (
	"context"
	"fmt"
	"tryffel.net/go/virtualpaper/errors"
	"tryffel.net/go/virtualpaper/models"
	"tryffel.net/go/virtualpaper/services/process"
	"tryffel.net/go/virtualpaper/storage"
)

type PropertyService struct {
	db      *storage.Database
	process *process.Manager
}

func NewPropertyService(db *storage.Database, manager *process.Manager) *PropertyService {
	return &PropertyService{
		db:      db,
		process: manager,
	}
}

func (s *PropertyService) GetProperties(ctx context.Context, userId int, page storage.Paging, sort storage.SortKey) (*[]models.Property, error) {
	return s.db.PropertyStore.GetProperties(s.db, userId, page, sort)
}

func (s *PropertyService) GetProperty(ctx context.Context, id int) (*models.Property, error) {
	return s.db.PropertyStore.GetProperty(s.db, id)
}

func (s *PropertyService) UserOwnsProperty(ctx context.Context, userId, id int) (bool, error) {
	return s.db.PropertyStore.UserOwnsProperty(s.db, userId, id)
}

func (s *PropertyService) AddDocumentProperty(ctx context.Context, document string, propertyId int, value string, description string) error {
	var err error
	tx, err := storage.NewTx(s.db, ctx)
	if err != nil {
		return err
	}
	defer tx.Close()

	property, err := s.db.PropertyStore.GetProperty(tx, propertyId)
	if err != nil {
		return fmt.Errorf("get property: %v", err)
	}

	generated := property.IsGenerated()
	if generated {
		value, err = property.Generate__Deprecated()
		if err != nil {
			return fmt.Errorf("generate value: %v", err)
		}
		description = "autogenerated"
	}
	err = s.db.PropertyStore.AddDocumentProperty(tx, property, document, value, description, generated)
	if err != nil {
		return fmt.Errorf("add property: %v", err)
	}
	return tx.Commit()
}

func (s *PropertyService) AddProperty(ctx context.Context, user *models.User, property *models.Property) error {
	validationError := errors.ErrInvalid

	if !user.IsAdmin && property.Global {
		validationError.ErrMsg = "user not admin"
		return validationError
	}

	err := s.db.PropertyStore.AddProperty(s.db, property)
	return err
}

func (s *PropertyService) UpdateProperty(ctx context.Context, property *models.Property) error {
	err := s.db.PropertyStore.UpdateProperty(s.db, property)
	return err
}
