name: Tests
on: push

env:
  VIRTUALPAPER_API_STATIC_CONTENT_PATH: "/app/frontend"
  VIRTUALPAPER_API_DISABLE_AUTH_RATELIMIT: true
  VIRTUALPAPER_PROCESSING_DATA_DIR: "/data"
  VIRTUALPAPER_PROCESSING_INPUT_DIR: "/input"
  VIRTUALPAPER_LOGGING_DIRECTORY: "/log"
  VIRTUALPAPER_PROCESSING_PANDOC_BIN: "/pandoc-2.18/bin/pandoc"
  VIRTUALPAPER_PROCESSING_PDFTOTEXT_BIN: "/usr/bin/pdftotext"
  VIRTUALPAPER_PROCESSING_IMAGICK_BIN: "/usr/bin/convert"
  VIRTUALPAPER_PROCESSING_TESSERACT_BIN: "/usr/bin/tesseract"
  VIRTUALPAPER_MEILISEARCH_URL: "http://meilisearch:7700"
  VIRTUALPAPER_DATABASE_HOST: postgres
  VIRTUALPAPER_DATABASE_PASSWORD: virtualpaper
  VIRTUALPAPER_DATABASE_DATABASE: virtualpaper
  VIRTUALPAPER_DATABASE_USERNAME: virtualpaper
  VIRTUALPAPER_DATABASE_NO_SSL: true
  VIRTUALPAPER_API_HOST: 0.0.0.0
  VIRTUALPAPER_LOGGING_LOG_LEVEL: DEBUG

jobs:
  tests:
    runs-on: ubuntu-latest
    container: tryffel/virtualpaper-drone:latest

    services:
      postgres:
        image: postgres:14.2-alpine3.15

        env:
          POSTGRES_USER: virtualpaper
          POSTGRES_PASSWORD: virtualpaper
          POSTGRES_DB: virtualpaper
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      meilisearch:
        image: getmeili/meilisearch:v1.7.6

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: go mod download

      - name: Unit tests
        run: make ci-test-unit

      - name: Init API tests
        run: |
             go run . migrate --config config.sample.toml
             go run . manage --config config.sample.toml add-user -U user -P superstronguser -a false
             go run . manage --config config.sample.toml add-user -U admin -P superstrongadmin -a true
             go run . manage --config config.sample.toml add-user -U tester -P superstrongtester -a false
             go run . index --config config.sample.toml

      - name: Run tests
        run: |
            go run . serve --config config.sample.toml &
            make ci-test-api

      - name: Test CLI
        run: |
             go run . migrate --config config.sample.toml
             go run . index --config config.sample.toml


